[env:seeed-xiao-nrf52840-sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200
lib_deps = 
	seeed-studio/Seeed Arduino LSM6DS3@^2.0.5
